# Generated by Django 3.2.13 on 2022-06-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('soil_texture', models.CharField(choices=[('AR', 'Argileux'), ('LA', 'Limono-Argileux'), ('AL', 'Argilo-Limoneux'), ('LM', 'Limoneux'), ('SL', 'Sablono-Limoneux'), ('SB', 'Sabloneux')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_identifier', models.CharField(default='', max_length=8)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MA', 'Materiel Agricole'), ('SS', 'Semences'), ('PL', 'Plants'), ('EC', 'Engrais Chimique'), ('EO', 'Engrais Organique'), ('PS', 'Pesticide-Acaricide'), ('HB', 'Herbicide'), ('FG', 'Fongicide')], max_length=2)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('S', 'Sender'), ('R', 'Receiver')], max_length=2)),
                ('key_identifier', models.CharField(default='', max_length=8)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_nodes', to='api.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('crop', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=200)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AT', 'Temperature/Air'), ('AH', 'Humidite/Air'), ('SM', 'Humidite/Sol'), ('SP', 'Ph/Sol'), ('SN', 'NPK/Sol'), ('HF', 'Humidite Foliaire')], max_length=2)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.node')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Sowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('crop', models.CharField(choices=[('TM', 'Tomate'), ('PT', 'Pomme de terre')], max_length=2)),
                ('quantity', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowings', to='api.sector')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowing_operations', to='api.input')),
            ],
        ),
        migrations.CreateModel(
            name='SoilPhSensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_phs', to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SoilNPKSensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=150)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_npks', to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureSensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moistures', to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phytosanitary_Treatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phytosanitary_treatements', to='api.sector')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phytosanitary_treatements', to='api.input')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.sector'),
        ),
        migrations.CreateModel(
            name='LeafWetnessSensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_wetnesses', to='api.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='api.stock'),
        ),
        migrations.CreateModel(
            name='Harvesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvestings', to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizing_operations', to='api.sector')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizing_operations', to='api.input')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='api.profile'),
        ),
        migrations.CreateModel(
            name='AirTemperatureSensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_temperatures', to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='AirHumiditySensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_humidities', to='api.sensor')),
            ],
        ),
    ]
