# Generated by Django 3.2.13 on 2022-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='key_identifier',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='node',
            name='key_identifier',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
