# Generated by Django 3.2.13 on 2022-06-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220607_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='key_identifier',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='node',
            name='key_identifier',
            field=models.CharField(max_length=8),
        ),
    ]
