# Generated by Django 3.2.13 on 2022-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220607_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
