# Generated by Django 3.2.13 on 2022-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='coordinates',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
