# Generated by Django 3.2.13 on 2022-06-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sector_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='crop',
            field=models.CharField(choices=[('TM', 'Tomate'), ('PT', 'Pomme de terre'), ('OI', 'Oignon'), ('PM', 'Pommier')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='crop',
            field=models.CharField(choices=[('TM', 'Tomate'), ('PT', 'Pomme de terre'), ('OI', 'Oignon'), ('PM', 'Pommier')], max_length=2),
        ),
    ]
