# Generated by Django 3.2.13 on 2022-06-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220627_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.farm'),
        ),
    ]
