# Generated by Django 3.2.13 on 2022-06-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_stock_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prelevements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_operation', models.CharField(choices=[('SS', 'Semences'), ('PL', 'Plants'), ('EC', 'Engrais Chimique'), ('EO', 'Engrais Organique'), ('PS', 'Pesticide-Acaricide'), ('HB', 'Herbicide'), ('FG', 'Fongicide')], max_length=2, null=True)),
                ('date', models.DateTimeField()),
                ('input_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelevements', to='api.stock')),
            ],
        ),
    ]
