# Generated by Django 3.2.13 on 2022-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220629_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
