# Generated by Django 3.2.13 on 2022-06-30 14:56

import api.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_identifier', models.CharField(default=api.utilities.key_generator, editable=False, max_length=6, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='type',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='key_identifier',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='node',
            name='key_identifier',
            field=models.CharField(max_length=6),
        ),
    ]
