# Generated by Django 3.2.13 on 2022-06-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220630_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('central', 'CENTRAL'), ('field', 'FIELD')], default='field', max_length=20),
        ),
    ]
