# Generated by Django 3.2.13 on 2022-06-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
