# Generated by Django 3.2.13 on 2022-07-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220701_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('AT', 'Temperature/Air'), ('AH', 'Humidite/Air'), ('SM', 'Humidite/Sol'), ('HF', 'Humidite Foliaire')], max_length=2),
        ),
    ]
