# Generated by Django 3.2.13 on 2022-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220704_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
