# Generated by Django 3.2.13 on 2022-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220704_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='longitude',
        ),
        migrations.AddField(
            model_name='farm',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
