# Generated by Django 3.2.13 on 2022-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220704_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='lng',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
