# Generated by Django 3.2.13 on 2022-07-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220704_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
