# Generated by Django 3.2.13 on 2022-07-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220704_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvesting',
            old_name='quantity',
            new_name='production',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='fertilizing',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fertilizing',
            name='mode_apport',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='harvesting',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='harvesting',
            name='production_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phytosanitary_treatement',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sowing',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='coordinates',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SoilLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_labors', to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhyto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MA', 'Materiel Agricole'), ('SS', 'Semences'), ('PL', 'Plants'), ('EC', 'Engrais Chimique'), ('EO', 'Engrais Organique'), ('PS', 'Pesticide-Acaricide'), ('HB', 'Herbicide'), ('FG', 'Fongicide')], max_length=2)),
                ('unit', models.CharField(max_length=10)),
                ('price_unit', models.FloatField()),
                ('quantity', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phyto_products', to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='MaterielVegetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MA', 'Materiel Agricole'), ('SS', 'Semences'), ('PL', 'Plants'), ('EC', 'Engrais Chimique'), ('EO', 'Engrais Organique'), ('PS', 'Pesticide-Acaricide'), ('HB', 'Herbicide'), ('FG', 'Fongicide')], max_length=2)),
                ('unit', models.CharField(max_length=10)),
                ('price_unit', models.FloatField()),
                ('quantity', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mv_products', to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('cost_unit', models.FloatField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MA', 'Materiel Agricole'), ('SS', 'Semences'), ('PL', 'Plants'), ('EC', 'Engrais Chimique'), ('EO', 'Engrais Organique'), ('PS', 'Pesticide-Acaricide'), ('HB', 'Herbicide'), ('FG', 'Fongicide')], max_length=2)),
                ('formula', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=10)),
                ('price_unit', models.FloatField()),
                ('quantity', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Desherbage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('type', models.CharField(max_length=10)),
                ('cost', models.FloatField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desherbage_operations', to='api.sector')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desherbage_operations', to='api.productphyto')),
            ],
        ),
        migrations.AlterField(
            model_name='fertilizing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizing_operations', to='api.fertilizer'),
        ),
        migrations.AlterField(
            model_name='phytosanitary_treatement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phytosanitary_treatements', to='api.productphyto'),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowing_operations', to='api.materielvegetal'),
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
