# Generated by Django 3.2.13 on 2022-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220707_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='formula',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
