# Generated by Django 3.2.13 on 2022-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_fertilizer_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='is_irrigation_automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
