# Generated by Django 3.2.13 on 2022-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220708_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesting',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='soillabor',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
