# Generated by Django 3.2.13 on 2022-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220712_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizing',
            name='mode_apport',
            field=models.CharField(choices=[('FT', 'Fertilization'), ('FG', 'Fertigation')], max_length=2, null=True),
        ),
    ]
