# Generated by Django 3.2.13 on 2022-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_fertilizing_mode_apport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesting',
            name='production_unit',
            field=models.CharField(choices=[('KG', 'Kilogrammes'), ('TN', 'Tonnes'), ('QN', 'Quintals')], max_length=2, null=True),
        ),
    ]
