# Generated by Django 3.2.13 on 2022-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_harvesting_production_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigation',
            name='duree',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='pluvio_fic',
            field=models.FloatField(null=True),
        ),
    ]
