# Generated by Django 3.2.13 on 2022-07-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220712_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField()),
                ('description', models.TextField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='api.sector')),
            ],
        ),
    ]
