# Generated by Django 3.2.13 on 2022-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='irrigation_cost_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='pluvio_fic',
            field=models.FloatField(null=True),
        ),
    ]
