# Generated by Django 3.2.13 on 2022-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220712_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='is_irrigation_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='last_irrigation',
            field=models.DateTimeField(null=True),
        ),
    ]
