# Generated by Django 3.2.13 on 2022-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220712_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='coordinates',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
