# Generated by Django 3.2.13 on 2022-07-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_sector_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelevements',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
