# Generated by Django 3.2.13 on 2022-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_prelevements_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='center',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='polygon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='crop',
            field=models.CharField(choices=[('TM', 'Tomate'), ('PT', 'Pomme de terre'), ('OI', 'Oignon'), ('PM', 'Pommier'), ('FR', 'Fraisier'), ('ML', 'Melon'), ('CR', 'Carotte'), ('PQ', 'Pastèque'), ('MS', 'Mais'), ('CL', 'Céréales'), ('PC', 'Pêcher'), ('AV', 'Avocatier'), ('OL', 'Olivier'), ('AM', 'Amandier'), ('CT', 'Citrouille'), ('PV', 'Poivron'), ('HR', 'Haricot'), ('CH', 'Chou'), ('NV', 'Navet'), ('BT', 'Betterave'), ('AL', 'Ail')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='crop',
            field=models.CharField(choices=[('TM', 'Tomate'), ('PT', 'Pomme de terre'), ('OI', 'Oignon'), ('PM', 'Pommier'), ('FR', 'Fraisier'), ('ML', 'Melon'), ('CR', 'Carotte'), ('PQ', 'Pastèque'), ('MS', 'Mais'), ('CL', 'Céréales'), ('PC', 'Pêcher'), ('AV', 'Avocatier'), ('OL', 'Olivier'), ('AM', 'Amandier'), ('CT', 'Citrouille'), ('PV', 'Poivron'), ('HR', 'Haricot'), ('CH', 'Chou'), ('NV', 'Navet'), ('BT', 'Betterave'), ('AL', 'Ail')], max_length=2),
        ),
    ]
