# Generated by Django 3.2.13 on 2022-07-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220716_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetationSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ndvi', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_satellites', to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='SolSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('surface_temp', models.FloatField()),
                ('temp_10cm', models.FloatField()),
                ('humidity_sol', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_satellites', to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='MeteoSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pression', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('uvi', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteo_satellites', to='api.sector')),
            ],
        ),
    ]
