# Generated by Django 3.2.13 on 2022-07-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_meteosatellite_solsatellite_vegetationsatellite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='coordinates',
        ),
    ]
